<a href="https://colab.research.google.com/github/Naitik1245/Machine_Learning/blob/main/Iris_Cross_Val.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.datasets import load_iris

In [2]:
flower=load_iris()

In [3]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=5)

In [6]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),flower.data,flower.target)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [8]:
cross_val_score(SVC(),flower.data,flower.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [10]:
cross_val_score(RandomForestClassifier(n_estimators=40),flower.data,flower.target)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [11]:
cross_val_score(RandomForestClassifier(n_estimators=10),flower.data,flower.target)

array([0.96666667, 0.96666667, 0.9       , 0.9       , 1.        ])