<a href="https://colab.research.google.com/github/Naitik1245/Machine_Learning/blob/main/K_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [6]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets  import load_digits
from sklearn.svm import SVC
digits=load_digits()

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [8]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [16]:
def get_score(model,x_train,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)

In [17]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [27]:
scores_l=[]
scores_SVM=[]
scores_rf=[]
for train_index,test_index in kf.split(digits.data):
  x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  scores_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
  scores_SVM.append(get_score(SVC(),x_train,x_test,y_train,y_test))
  scores_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))



In [28]:
scores_rf

[0.9348914858096828, 0.9549248747913188, 0.9248747913188647]

In [29]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [32]:
scores_SVM

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [34]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=6)

array([0.92      , 0.92333333, 0.92      , 0.9632107 , 0.93311037,
       0.90301003])

In [35]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)

array([0.85555556, 0.78888889, 0.8718663 , 0.90529248, 0.86629526])

In [36]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93888889, 0.91666667, 0.95821727, 0.9637883 , 0.91643454])